<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\audio\sillycatgotthemMOVES.wav" />
    <None Remove="Assets\idle_1.png" />
    <None Remove="Assets\idle_2.png" />
    <None Remove="Assets\idle_3.png" />
    <None Remove="Assets\idle_4.png" />
    <None Remove="Assets\walkLeft_1.png" />
    <None Remove="Assets\walkLeft_2.png" />
    <None Remove="Assets\walkLeft_3.png" />
    <None Remove="Assets\walkLeft_4.png" />
    <None Remove="Assets\walkRight_1.png" />
    <None Remove="Assets\walkRight_2.png" />
    <None Remove="Assets\walkRight_3.png" />
    <None Remove="Assets\walkRight_4.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\audio\sillycatgotthemMOVES.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\idle_1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\idle_2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\idle_3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\idle_4.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\walkLeft_1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\walkLeft_2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\walkLeft_3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\walkLeft_4.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\walkRight_1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\walkRight_2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\walkRight_3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\walkRight_4.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>